### ISSUE TITLE
Cant install via composer

### ISSUE THREAD

**Issue by re8us** [anmaslov/yii2-autocomplete-widget#2]
It's look like you have a typo in version. 

I think you should use v1.1 instead v.1.1

https://getcomposer.org/doc/04-schema.md#version

**Comment by re8us** [comment]
I have to use version `"*@dev"` to install

**Comment by anmaslov** [comment]
@re8us , thanks, i was rename release to v1.1

**Comment by re8us** [comment]
thanks, works!
